### ISSUE TITLE
https://shnhz.github.io/shn-ui/#/component/vue-cropper 裁剪不支持png图吗 上传png裁剪都是黑色了 背景

### ISSUE THREAD

**Issue by a6965921** [ShnHz/shn-ui#6]
https://shnhz.github.io/shn-ui/#/component/vue-cropper 裁剪不支持png图吗 上传png裁剪都是黑色了 背景

**Comment by ShnHz** [comment]
可以去插件官方提一个issues，https://github.com/xyxiao001/vue-cropper，我这边只是做了一个vue-cropper的教程～
